spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrzhangxisheng/spring_cloud_config/  #git配置文件地址  地址可用,可以参考
          searchPaths: spring_cloud_config #配置文件的文件夹   
          username: git帐号
          password: git密码
server:
  port: 86

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
